name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-versioning:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: test
        run: |
          ./ci/test-versioning.sh
